### ISSUE TITLE
dafscnn error

### ISSUE THREAD

**Issue by jasmit64** [satoken/dafs#2]
facing dafscnn error
![screenshot from 2018-12-07 18-11-17](https://user-images.githubusercontent.com/45158270/49650859-a149d480-fa53-11e8-8385-0a9e51cfd120.png)
![screenshot from 2018-12-07 18-42-05](https://user-images.githubusercontent.com/45158270/49650861-a149d480-fa53-11e8-86be-8ffbe0ff4190.png)

tried running on different machine, but same error coming of dafscnn not found

**Comment by satoken** [comment]
dafscnn is a variant of DAFS, but is not my project.
Please contact the corresponding author of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6022636/
