### ISSUE TITLE
Error in making the dafs file

### ISSUE THREAD

**Issue by jasmit64** [satoken/dafs#3]
there is error when i am trying to configure and make,
Can you tell what is the configuration of the computer needed to run the make file of dafs

**Comment by satoken** [comment]
I cannot give you any advices because I have no information about your environment where you build DAFS. Please first read README.md carefully.

**Comment by KennthShang** [comment]
![image](https://user-images.githubusercontent.com/22445402/80569869-59529580-8a2c-11ea-9793-6ca9c377a65c.png)
There is an error when I try to "make" the file. The system is Linux. Could you please help me solve the problem?

**Comment by satoken** [comment]
I'm trying to change to building using cmake, since building using configure has been giving me a lot of trouble so far.
The code using cmake is included in the dev branch, so please try it here.

Thanks,
