### ISSUE TITLE
Failed to build Docker image out of the Dockerfile in the repository

### ISSUE THREAD

**Issue by tzok** [satoken/dafs#5]
I tried to build a Docker image (`docker build -t dafs .`) from the _master_ branch, but there is an error during DAFS compilation:

```
(...)
[ 65%] Building CXX object src/CMakeFiles/dafs.dir/dafs.cpp.o
/workspaces/src/dafs.cpp:59:10: fatal error: cxxopts.hpp: No such file or directory
   59 | #include "cxxopts.hpp"
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/dafs.dir/build.make:121: src/CMakeFiles/dafs.dir/dafs.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:177: src/CMakeFiles/dafs.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

**Comment by satoken** [comment]
Could it be that the clone of the submodules have not been performed? Please try executing `git clone --recursive https://github.com/satoken/dafs.git` and then run `docker build -t dafs .`

**Comment by tzok** [comment]
Thank you for pointing it out. I now realize that I downloaded the ZIP file instead of cloning the repository, and as a result, I did not notice the submodule icons in the GitHub UI. Once I cloned the repository with submodules, the Docker builds without any issues. I appreciate your prompt response and the high-quality science and software you have provided!
